"""empty message

Revision ID: f11caf9d0db6
Revises: 46b35fb20e61
Create Date: 2016-01-16 16:14:23.629499

"""

# revision identifiers, used by Alembic.
revision = 'f11caf9d0db6'
down_revision = '46b35fb20e61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film_genre',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], )
    )
    op.drop_constraint(u'films_genre_id_fkey', 'films', type_='foreignkey')
    op.drop_column(u'films', 'genre_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'films', sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'films_genre_id_fkey', 'films', 'genres', ['genre_id'], ['id'])
    op.drop_table('film_genre')
    ### end Alembic commands ###
