"""empty message

Revision ID: fc8bb888ca45
Revises: f11caf9d0db6
Create Date: 2016-01-16 18:06:56.196276

"""

# revision identifiers, used by Alembic.
revision = 'fc8bb888ca45'
down_revision = 'f11caf9d0db6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'director')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('director', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
